name: 'Delete all installed iOS certificates and provisioning profile'
description: 'Delete all installed iOS certificates and provisioning profile'

runs:
  using: 'composite'
  steps:
      - name: Clean up keychain and provisioning profile
        shell: bash
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
