name: 'Cache gradle dependencies'
description: 'Cache gradle dependencies to reduce build time'
runs:
  using: 'composite'
  steps:
      # Taken from https://github.com/actions/cache/blob/main/examples.md#java---gradle
    - name: Cache gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-