name: Mobile - Push to main branch

on:
  pull_request:
    types: [ closed ] # Warning: close event is triggered when closing or merging a PR
    branches: [ main ]

concurrency:
  group: push-mobile-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releaseVersion: ${{ steps.create-release.outputs.releaseVersion }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup git config
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: ./.github/actions/create-github-release
        id: create-release
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  prod:
    uses: ./.github/workflows/reus-platforms-env-update.yaml
    needs: [ create-release ]
    with:
      github_env: prod
      android_release_file_path: build/app/outputs/bundle/release/
    secrets: inherit